//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Adjunto {
  idAdjunto?: number;
  nombreArchivo?: string | undefined;
  extension?: string | undefined;
  mimeType?: string | undefined;
  tamaniobytes?: number | undefined;
  ruta?: string | undefined;
  producto?: Producto[] | undefined;
  usuario?: Usuario[] | undefined;
}

export interface AuthCredentials {
  username?: string | undefined;
  password?: string | undefined;
}

export interface DeleteAdjuntoCommand {
  idAdjunto?: number;
}

export interface DeleteHorariosCommand {
  idHorarios?: number;
}

export interface DeleteMaquinaCommand {
  idMaquinas?: number;
}

export interface DeleteUsuarioCommand {
  idUsuario?: number;
}

export interface Detallepedido {
  idDetallePedido?: number;
  idPedidos?: number;
  idProductos?: number;
  cantidad?: number | undefined;
  precioUnitario?: number | undefined;
  subtotal?: number | undefined;
  idPedidosNavigation?: Pedido;
  idProductosNavigation?: Producto;
}

export interface Factura {
  idFactura?: number;
  idUsuario?: number;
  idReservas?: number;
  idPedidos?: number;
  fechaFactura?: Date;
  montoTotal?: number;
  idPedidosNavigation?: Pedido;
  idReservasNavigation?: Reserva;
  idUsuarioNavigation?: Usuario;
}

export interface FacturaCommand {
  idFactura?: number;
  idUsuario?: number;
  idReservas?: number;
  idPedidos?: number;
  fechaFactura?: Date;
  montoTotal?: number;
}

export interface Horarios {
  idHorarios?: number;
  idMaquinas?: number;
  horaInicio?: string;
  horaFin?: string;
  precio?: number;
  idMaquinasNavigation?: Maquinas;
}

export interface HorariosCommand {
  horarios?: HorariosCommandItem[] | undefined;
}

export interface HorariosCommandItem {
  idHorarios?: number | undefined;
  idMaquinas?: number;
  horaInicio?: string;
  horaFin?: string;
  precio?: number;
}

export enum HttpStatusCode {
  _100 = 100,
  _101 = 101,
  _102 = 102,
  _103 = 103,
  _200 = 200,
  _201 = 201,
  _202 = 202,
  _203 = 203,
  _204 = 204,
  _205 = 205,
  _206 = 206,
  _207 = 207,
  _208 = 208,
  _226 = 226,
  _300 = 300,
  _301 = 301,
  _302 = 302,
  _303 = 303,
  _304 = 304,
  _305 = 305,
  _306 = 306,
  _307 = 307,
  _308 = 308,
  _400 = 400,
  _401 = 401,
  _402 = 402,
  _403 = 403,
  _404 = 404,
  _405 = 405,
  _406 = 406,
  _407 = 407,
  _408 = 408,
  _409 = 409,
  _410 = 410,
  _411 = 411,
  _412 = 412,
  _413 = 413,
  _414 = 414,
  _415 = 415,
  _416 = 416,
  _417 = 417,
  _421 = 421,
  _422 = 422,
  _423 = 423,
  _424 = 424,
  _426 = 426,
  _428 = 428,
  _429 = 429,
  _431 = 431,
  _451 = 451,
  _500 = 500,
  _501 = 501,
  _502 = 502,
  _503 = 503,
  _504 = 504,
  _505 = 505,
  _506 = 506,
  _507 = 507,
  _508 = 508,
  _510 = 510,
  _511 = 511,
}

export interface MaquinaCommand {
  idMaquinas?: number | undefined;
  nombreMaquina?: string | undefined;
  esActivo?: boolean | undefined;
}

export interface Maquinas {
  idMaquinas?: number;
  nombreMaquina?: string | undefined;
  esActivo?: boolean | undefined;
  horarios?: Horarios[] | undefined;
  reserva?: Reserva[] | undefined;
}

export interface Pedido {
  idPedidos?: number;
  idUsuario?: number;
  fechaPedido?: Date;
  total?: number;
  esActivo?: boolean;
  detallepedido?: Detallepedido[] | undefined;
  factura?: Factura[] | undefined;
  idUsuarioNavigation?: Usuario;
}

export interface PedidoCommand {
  idPedidos?: number | undefined;
  idUsuario?: number;
  fechaPedido?: Date;
  total?: number;
  esActivo?: boolean;
}

export interface Persona {
  idPersonas?: number;
  identificacion?: string | undefined;
  nombres?: string | undefined;
  apellidos?: string | undefined;
  numeroCelular?: string | undefined;
  correoElectronico?: string | undefined;
  direccion?: string | undefined;
  sexo?: string | undefined;
  esActivo?: boolean;
  usuario?: Usuario[] | undefined;
}

export interface Producto {
  idProductos?: number;
  idAdjuntos?: number;
  nombreProdcuto?: string | undefined;
  precio?: number;
  stock?: number;
  esActivo?: boolean | undefined;
  detallepedido?: Detallepedido[] | undefined;
  idAdjuntosNavigation?: Adjunto;
}

export interface ProductosCommand {
  idProductos?: number;
  nombreProdcuto?: string | undefined;
  precio?: number;
  stock?: number;
  esActivo?: boolean | undefined;
}

export interface Reserva {
  idReservas?: number;
  idUsuario?: number;
  idMaquinas?: number;
  fechaReserv?: Date;
  total?: number;
  esActivo?: boolean;
  factura?: Factura[] | undefined;
  idMaquinasNavigation?: Maquinas;
  idUsuarioNavigation?: Usuario;
}

export interface ReservasCommand {
  idReservas?: number | undefined;
  idUsuario?: number;
  idMaquinas?: number;
  fechaReserv?: Date;
  total?: number;
  esActivo?: boolean;
}

export interface Rol {
  idRol?: number;
  descripcion?: string | undefined;
  esAdministrador?: boolean;
  esActivo?: boolean;
  usuario?: Usuario[] | undefined;
}

export interface RolCommand {
  idRol?: number | undefined;
  descripcion?: string | undefined;
  esAdministrador?: boolean;
  esActivo?: boolean;
}

export interface SetPersonasCommand {
  idPersonas?: number | undefined;
  identificacion?: string | undefined;
  nombres?: string | undefined;
  apellidos?: string | undefined;
  numeroCelular?: string | undefined;
  correoElectronico?: string | undefined;
  direccion?: string | undefined;
  sexo?: string | undefined;
  esActivo?: boolean;
}

export interface SetUsuarioCommand {
  idUsuario?: number | undefined;
  idPersonas?: number;
  idRol?: number | undefined;
  nombreUsuario?: string | undefined;
  clave?: string | undefined;
  esActivo?: boolean;
}

export interface Usuario {
  idUsuario?: number;
  idAdjunto?: number | undefined;
  idPersonas?: number;
  idRol?: number | undefined;
  nombreUsuario?: string | undefined;
  clave?: string | undefined;
  esActivo?: boolean;
  factura?: Factura[] | undefined;
  idAdjuntoNavigation?: Adjunto;
  idPersonasNavigation?: Persona;
  idRolNavigation?: Rol;
  pedido?: Pedido[] | undefined;
  reserva?: Reserva[] | undefined;
}

export interface UsuarioResponse {
  idUsuario?: number;
  idPersonas?: number;
  nombreUsuario?: string | undefined;
  esActivo?: boolean | undefined;
  token?: string | undefined;
  personas?: Persona;
}

export interface UsuarioResponseResponse {
  isSuccess?: boolean;
  statusCode?: HttpStatusCode;
  message?: string | undefined;
  Errores?: string[] | undefined;
  data?: UsuarioResponse;
  errores?: { [key: string]: string[]; } | undefined;
}

export interface FileParameter {
  data: any;
  fileName: string;
}
