// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Horario
{
    public int IdHorarios { get; set; }

    public int IdMaquinas { get; set; }

    public TimeOnly HoraInicio { get; set; }

    public TimeOnly HoraFin { get; set; }

    public decimal Precio { get; set; }

    public virtual Maquina IdMaquinasNavigation { get; set; }
}