// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Maquina
{
    public int IdMaquinas { get; set; }

    public string NombreMaquina { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<Horario> Horarios { get; set; } = new List<Horario>();

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}