// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Pedido
{
    public int IdPedidos { get; set; }

    public int IdUsuario { get; set; }

    public DateTime FechaPedido { get; set; }

    public decimal Total { get; set; }

    public sbyte EsActivo { get; set; }

    public virtual ICollection<Detallepedido> Detallepedidos { get; set; } = new List<Detallepedido>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Usuario IdUsuarioNavigation { get; set; }
}