// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Persona
{
    public int IdPersonas { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string NumeroCelular { get; set; }

    public string CorreoElectronico { get; set; }

    public string Direccion { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}