// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Producto
{
    public int IdProductos { get; set; }

    public string NombreProdcuto { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<Detallepedido> Detallepedidos { get; set; } = new List<Detallepedido>();
}