// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm_esport_zone.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public int IdPersonas { get; set; }

    public string NombreUsuario { get; set; }

    public string Clave { get; set; }

    public int IdRol { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Persona IdPersonasNavigation { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}